name: Auto Assign Reviewers

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  assign_reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Assign reviewers
        uses: kentaro-m/auto-assign-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reviewers: 'mirassafadi, yunatanhaj, KamelDokh, Dima-Haj, amiiraothman'
