name: Auto Assign Reviewers

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  assign_reviewers:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Assign reviewers
        uses: kentaro-m/auto-assign-action@v2.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}  # Authentication token
          configuration-path: .github/auto_assign.yml  # Path to the configuration file

